name: Publish Sourcemaps to Sentry
description: Copy sourcemaps from docker image and publish to Sentry under the images relase tag.
author: itsmycargo
branding:
  color: blue
  icon: layers

inputs:
  repository-tag:
    description: Full tag for the image to be loaded
    required: true
  registry_password:
    description: “Password for image registry”
    required: true
  aws-access-key-id:
    description: AWS Access Key ID for login and pushing to ECR Repository
    required: true
  aws-secret-access-key:
    description: AWS Access Key for login and pushing to ECR Repository
    required: true
  aws-region:
    description: AWS Region for ECR Repository
    required: true
  path:
    description: Path in the image where the sourcemaps can be found
    required: true
  sentry-auth-token:
    description: Token for authenticating with Sentry.io
    required: true
  sentry-org:
    description: Name of the organization in Sentry.io
    required: true
  sentry-project:
    description: Name of the project in Sentry.io
    required: true

outputs:
  release:
    description: Sentry Release
    value: ${{ steps.meta.outputs.release }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - uses: aws-actions/amazon-ecr-login@v1

    - id: make-directory
      run: mkdir dist
      shell: bash

    - id: create-container
      run:
        docker create --name=temp_docker ${{ inputs.repository-tag }}
      shell: bash

    - id: copy-source-files
      run:
        docker cp temp_docker:${{ inputs.path }} ./dist
      shell: bash

    - id: destroy-container
      run:
        docker rm temp_docker
      shell: bash

    - uses: getsentry/action-release@v1
      with:
        sourcemaps: './dist'
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        SENTRY_ORG: ${{ inputs.sentry-org }}
        SENTRY_PROJECT: ${{ inputs.sentry-project }}